In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## Define the vocabulary size
voc_size=10000

In [19]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5005, 1895, 7388, 7504],
 [5005, 1895, 7388, 9688],
 [5005, 2783, 7388, 5062],
 [9032, 4070, 6958, 6547, 9240],
 [9032, 4070, 6958, 6547, 440],
 [1492, 5005, 3951, 7388, 3965],
 [1732, 3813, 3445, 6547]]

In [20]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [22]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5005 1895 7388 7504]
 [   0    0    0    0 5005 1895 7388 9688]
 [   0    0    0    0 5005 2783 7388 5062]
 [   0    0    0 9032 4070 6958 6547 9240]
 [   0    0    0 9032 4070 6958 6547  440]
 [   0    0    0 1492 5005 3951 7388 3965]
 [   0    0    0    0 1732 3813 3445 6547]]


In [23]:
## feature representation
dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 28ms/step


array([[[-0.04163031, -0.01574655, -0.03238603, -0.03496566,
         -0.04840551, -0.04090322,  0.01444899,  0.04933329,
         -0.04360357, -0.01997601],
        [-0.04163031, -0.01574655, -0.03238603, -0.03496566,
         -0.04840551, -0.04090322,  0.01444899,  0.04933329,
         -0.04360357, -0.01997601],
        [-0.04163031, -0.01574655, -0.03238603, -0.03496566,
         -0.04840551, -0.04090322,  0.01444899,  0.04933329,
         -0.04360357, -0.01997601],
        [-0.04163031, -0.01574655, -0.03238603, -0.03496566,
         -0.04840551, -0.04090322,  0.01444899,  0.04933329,
         -0.04360357, -0.01997601],
        [-0.00944265,  0.03015831, -0.03344433,  0.03191454,
         -0.02170471,  0.00661946,  0.04651821,  0.04187873,
          0.02692559,  0.04467419],
        [ 0.01325658,  0.01355905,  0.02145565, -0.03594953,
         -0.00516511, -0.0060467 ,  0.0301868 ,  0.03968986,
         -0.01475728,  0.0273378 ],
        [-0.01438391,  0.01178952,  0.0304455 ,  0.0

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 5005, 1895, 7388, 7504], dtype=int32)

In [28]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 31ms/step


array([[-0.04163031, -0.01574655, -0.03238603, -0.03496566, -0.04840551,
        -0.04090322,  0.01444899,  0.04933329, -0.04360357, -0.01997601],
       [-0.04163031, -0.01574655, -0.03238603, -0.03496566, -0.04840551,
        -0.04090322,  0.01444899,  0.04933329, -0.04360357, -0.01997601],
       [-0.04163031, -0.01574655, -0.03238603, -0.03496566, -0.04840551,
        -0.04090322,  0.01444899,  0.04933329, -0.04360357, -0.01997601],
       [-0.04163031, -0.01574655, -0.03238603, -0.03496566, -0.04840551,
        -0.04090322,  0.01444899,  0.04933329, -0.04360357, -0.01997601],
       [-0.00944265,  0.03015831, -0.03344433,  0.03191454, -0.02170471,
         0.00661946,  0.04651821,  0.04187873,  0.02692559,  0.04467419],
       [ 0.01325658,  0.01355905,  0.02145565, -0.03594953, -0.00516511,
        -0.0060467 ,  0.0301868 ,  0.03968986, -0.01475728,  0.0273378 ],
       [-0.01438391,  0.01178952,  0.0304455 ,  0.03285987,  0.0392834 ,
        -0.01149931, -0.01106069,  0.03449973